ci(publish-to-release): restore during publish
The optimization of restoring once instead of during each publish did
not work as expected.  It caused the [workflow run to fail] with the
error message:

    Error: /usr/share/dotnet/sdk/10.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file '/home/runner/work/ImdbPosterDownloader/ImdbPosterDownloader/ImdbPosterDownloader/obj/project.assets.json' doesn't have a target for 'net10.0/linux-x64'. Ensure that restore has run and that you have included 'net10.0' in the TargetFrameworks for your project. You may also need to include 'linux-x64' in your project's RuntimeIdentifiers. [/home/runner/work/ImdbPosterDownloader/ImdbPosterDownloader/ImdbPosterDownloader/ImdbPosterDownloader.csproj]

To avoid this, restore during publish.

[workflow run to fail]: https://github.com/kevinoid/ImdbPosterDownloader/actions/runs/28833288509/job/85511631252

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>